In [1]:
import pandas as pd


In [2]:
df=pd.read_csv("/content/drive/MyDrive/Concrete/Concrete_Data.csv")
df

Cement (component 1)(kg in a m^3 mixture)  \
0                                         540.0   
1                                         540.0   
2                                         332.5   
3                                         332.5   
4                                         198.6   
...                                         ...   
1025                                      276.4   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Water  (component 4)(kg in a m^3 mixture)  \
0                                         162.0   
1                                         162.0   
2                                         228.0   
3                                         228.0   
4                                         192.0   
...                                         ...   
1025                                      179.6   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                   0.0     
1                                                   0.0     
2                                                   0.0     
3                                                   0.0     
4                                                   0.0     
...                                                 ...     
1025                                                8.9     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                                1040.0      
1                                                1055.0      
2                                                 932.0      
3                                                 932.0      
4                                                 978.4      
...                                                 ...      
1025                                              870.1      
1026                                              817.9      
1027                                              892.4      
1028                                              989.6      
1029                                              864.5      

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                                 676.0         28   
1                                                 676.0         28   
2                                                 594.0        270   
3                                                 594.0        365   
4                                                 825.5        360   
...                                                 ...        ...   
1025                                              768.3         28   
1026                                              813.4         28   
1027                                              780.0         28   
1028                                              788.9         28   
1029                                              761.5         28   

      Concrete strength   
0                  79.99  
1                  61.89  
2                  40.27  
3                  41.05  
4                  44.30  
...                  ...  
1025               44.28  
1026               31.18  
1027               23.70  
1028               32.77  
1029               32.40  

[1030 rows x 7 columns]

In [3]:
def map_strength_to_grade(strength):
    if strength < 15:
        return 'C15'
    elif 15 <= strength < 25:
        return 'C15'
    elif 20 <= strength < 30:
        return 'C20'
    elif 25 <= strength < 40:
        return 'C25'
    elif 30 <= strength < 50:
        return 'C30'
    elif 35 <= strength < 60:
        return 'C35'
    elif 40 <= strength < 80:
        return 'C40'
    else:
        return 'C15'


In [4]:

print(df.columns.tolist())


['Cement (component 1)(kg in a m^3 mixture)', 'Water  (component 4)(kg in a m^3 mixture)', 'Superplasticizer (component 5)(kg in a m^3 mixture)', 'Coarse Aggregate  (component 6)(kg in a m^3 mixture)', 'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'Age (day)', 'Concrete strength ']


In [5]:
df['Grade'] = df['Concrete strength '].apply(map_strength_to_grade)


In [6]:
# 5. Preview the result
print(df[['Concrete strength ', 'Grade']].head())
print(df['Grade'].value_counts())

   Concrete strength  Grade
0               79.99   C40
1               61.89   C40
2               40.27   C30
3               41.05   C30
4               44.30   C30
Grade
C15    298
C25    253
C30    169
C35    116
C20    103
C40     91
Name: count, dtype: int64


In [7]:
df

Cement (component 1)(kg in a m^3 mixture)  \
0                                         540.0   
1                                         540.0   
2                                         332.5   
3                                         332.5   
4                                         198.6   
...                                         ...   
1025                                      276.4   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Water  (component 4)(kg in a m^3 mixture)  \
0                                         162.0   
1                                         162.0   
2                                         228.0   
3                                         228.0   
4                                         192.0   
...                                         ...   
1025                                      179.6   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                   0.0     
1                                                   0.0     
2                                                   0.0     
3                                                   0.0     
4                                                   0.0     
...                                                 ...     
1025                                                8.9     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                                1040.0      
1                                                1055.0      
2                                                 932.0      
3                                                 932.0      
4                                                 978.4      
...                                                 ...      
1025                                              870.1      
1026                                              817.9      
1027                                              892.4      
1028                                              989.6      
1029                                              864.5      

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                                 676.0         28   
1                                                 676.0         28   
2                                                 594.0        270   
3                                                 594.0        365   
4                                                 825.5        360   
...                                                 ...        ...   
1025                                              768.3         28   
1026                                              813.4         28   
1027                                              780.0         28   
1028                                              788.9         28   
1029                                              761.5         28   

      Concrete strength  Grade  
0                  79.99   C40  
1                  61.89   C40  
2                  40.27   C30  
3                  41.05   C30  
4                  44.30   C30  
...                  ...   ...  
1025               44.28   C30  
1026               31.18   C25  
1027               23.70   C15  
1028               32.77   C25  
1029               32.40   C25  

[1030 rows x 8 columns]

In [8]:
df = df[df['Grade'].isin(['C15', 'C20', 'C25'])]


In [9]:
df

Cement (component 1)(kg in a m^3 mixture)  \
7                                         380.0   
9                                         475.0   
10                                        198.6   
11                                        198.6   
16                                        139.6   
...                                         ...   
1024                                      166.0   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Water  (component 4)(kg in a m^3 mixture)  \
7                                         228.0   
9                                         228.0   
10                                        192.0   
11                                        192.0   
16                                        192.0   
...                                         ...   
1024                                      183.2   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
7                                                   0.0     
9                                                   0.0     
10                                                  0.0     
11                                                  0.0     
16                                                  0.0     
...                                                 ...     
1024                                               12.7     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
7                                                 932.0      
9                                                 932.0      
10                                                978.4      
11                                                978.4      
16                                               1047.0      
...                                                 ...      
1024                                              858.8      
1026                                              817.9      
1027                                              892.4      
1028                                              989.6      
1029                                              864.5      

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
7                                                 594.0         28   
9                                                 594.0         28   
10                                                825.5         90   
11                                                825.5         28   
16                                                806.9         90   
...                                                 ...        ...   
1024                                              826.8         28   
1026                                              813.4         28   
1027                                              780.0         28   
1028                                              788.9         28   
1029                                              761.5         28   

      Concrete strength  Grade  
7                  36.45   C25  
9                  39.29   C25  
10                 38.07   C25  
11                 28.02   C20  
16                 39.36   C25  
...                  ...   ...  
1024               37.92   C25  
1026               31.18   C25  
1027               23.70   C15  
1028               32.77   C25  
1029               32.40   C25  

[654 rows x 8 columns]

In [ ]:
# Define features and target
features = [ 'Cement (component 1)(kg in a m^3 mixture)',
            'Water  (component 4)(kg in a m^3 mixture)',
            'Superplasticizer (component 5)(kg in a m^3 mixture)',
             'Coarse Aggregate  (component 6)(kg in a m^3 mixture)',
             'Fine Aggregate (component 7)(kg in a m^3 mixture)',
             'Age (day)'
]

X = df[features]
y = df['Grade']


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',  # 🔥 This tells the model to handle class imbalance
    random_state=42
)

model.fit(X_train, y_train)


RandomForestClassifier(class_weight='balanced', random_state=42)

In [ ]:
#from sklearn.ensemble import RandomForestClassifier

#model = RandomForestClassifier(n_estimators=100, random_state=42)
#model.fit(X_train, y_train)


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

         C15       0.76      0.84      0.80        56
         C20       0.55      0.23      0.32        26
         C25       0.74      0.88      0.80        49

    accuracy                           0.73       131
   macro avg       0.68      0.65      0.64       131
weighted avg       0.71      0.73      0.71       131

Confusion Matrix:
[[47  3  6]
 [11  6  9]
 [ 4  2 43]]


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Encode the target variable
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)


In [ ]:
model.fit(X_train, y_train_encoded)
y_pred_encoded = model.predict(X_test)


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [17:41:36] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


In [ ]:
y_pred = le.inverse_transform(y_pred_encoded)

# Evaluate using original labels
from sklearn.metrics import classification_report, confusion_matrix
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

         C15       0.75      0.88      0.81        56
         C20       0.60      0.23      0.33        26
         C25       0.77      0.88      0.82        49

    accuracy                           0.75       131
   macro avg       0.71      0.66      0.65       131
weighted avg       0.73      0.75      0.72       131

Confusion Matrix:
 [[49  2  5]
 [12  6  8]
 [ 4  2 43]]


In [10]:
dfs=pd.read_csv("/content/drive/MyDrive/Concrete/c20_concrete.csv")
dfs

Cement (component 1)(kg in a m^3 mixture)  \
0                                   309.934283   
1                                   297.234714   
2                                   312.953771   
3                                   330.460597   
4                                   295.316933   
..                                         ...   
495                                 310.778201   
496                                 279.255077   
497                                 296.193226   
498                                 282.487635   
499                                 272.344005   

     Water (component 4)(kg in a m^3 mixture)  \
0                                  189.261775   
1                                  199.094166   
2                                  166.014324   
3                                  185.629692   
4                                  173.493574   
..                                        ...   
495                                177.188997   
496                                197.976865   
497                                186.408429   
498                                174.288210   
499                                185.725828   

     Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                             7.798711     
1                                             6.849267     
2                                             5.119261     
3                                             3.706126     
4                                             6.396447     
..                                                 ...     
495                                           9.012186     
496                                           9.123007     
497                                           7.416732     
498                                           7.048125     
499                                           6.185054     

     Coarse Aggregate (component 6)(kg in a m^3 mixture)  \
0                                           988.918054     
1                                           922.440714     
2                                           909.090056     
3                                           949.831277     
4                                           941.490769     
..                                                 ...     
495                                        1003.507512     
496                                         948.673937     
497                                         905.906267     
498                                         941.846652     
499                                         912.754868     

     Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day) Grade  
0                                           722.992869         56   C20  
1                                           744.219253         28   C20  
2                                           718.303203         14   C20  
3                                           737.681539         14   C20  
4                                           674.255413         28   C20  
..                                                 ...        ...   ...  
495                                         782.528208         14   C20  
496                                         738.841483         28   C20  
497                                         738.809593         56   C20  
498                                         781.614876         14   C20  
499                                         763.602052         28   C20  

[500 rows x 7 columns]

In [11]:
df

Cement (component 1)(kg in a m^3 mixture)  \
7                                         380.0   
9                                         475.0   
10                                        198.6   
11                                        198.6   
16                                        139.6   
...                                         ...   
1024                                      166.0   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Water  (component 4)(kg in a m^3 mixture)  \
7                                         228.0   
9                                         228.0   
10                                        192.0   
11                                        192.0   
16                                        192.0   
...                                         ...   
1024                                      183.2   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
7                                                   0.0     
9                                                   0.0     
10                                                  0.0     
11                                                  0.0     
16                                                  0.0     
...                                                 ...     
1024                                               12.7     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
7                                                 932.0      
9                                                 932.0      
10                                                978.4      
11                                                978.4      
16                                               1047.0      
...                                                 ...      
1024                                              858.8      
1026                                              817.9      
1027                                              892.4      
1028                                              989.6      
1029                                              864.5      

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
7                                                 594.0         28   
9                                                 594.0         28   
10                                                825.5         90   
11                                                825.5         28   
16                                                806.9         90   
...                                                 ...        ...   
1024                                              826.8         28   
1026                                              813.4         28   
1027                                              780.0         28   
1028                                              788.9         28   
1029                                              761.5         28   

      Concrete strength  Grade  
7                  36.45   C25  
9                  39.29   C25  
10                 38.07   C25  
11                 28.02   C20  
16                 39.36   C25  
...                  ...   ...  
1024               37.92   C25  
1026               31.18   C25  
1027               23.70   C15  
1028               32.77   C25  
1029               32.40   C25  

[654 rows x 8 columns]

In [12]:
# Combine them (row-wise)
combined_df = pd.concat([df, dfs], ignore_index=True)

# Save the merged dataset to a new file
combined_df.to_csv('combined_concrete_data.csv', index=False)

print("Successfully merged both datasets and saved as 'combined_concrete_data.csv'")

Successfully merged both datasets and saved as 'combined_concrete_data.csv'


In [60]:
combined_df

Cement (component 1)(kg in a m^3 mixture)  \
0                                    380.000000   
1                                    475.000000   
2                                    198.600000   
3                                    198.600000   
4                                    139.600000   
...                                         ...   
1149                                 310.778201   
1150                                 279.255077   
1151                                 296.193226   
1152                                 282.487635   
1153                                 272.344005   

      Superplasticizer (component 5)(kg in a m^3 mixture)  Coarse Aggregate  \
0                                              0.000000          932.000000   
1                                              0.000000          932.000000   
2                                              0.000000          978.400000   
3                                              0.000000          978.400000   
4                                              0.000000         1047.000000   
...                                                 ...                 ...   
1149                                           9.012186         1003.507512   
1150                                           9.123007          948.673937   
1151                                           7.416732          905.906267   
1152                                           7.048125          941.846652   
1153                                           6.185054          912.754868   

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day) Grade  \
0                                            594.000000         28   C25   
1                                            594.000000         28   C25   
2                                            825.500000         90   C25   
3                                            825.500000         28   C20   
4                                            806.900000         90   C25   
...                                                 ...        ...   ...   
1149                                         782.528208         14   C20   
1150                                         738.841483         28   C20   
1151                                         738.809593         56   C20   
1152                                         781.614876         14   C20   
1153                                         763.602052         28   C20   

      Water Duplicte  
0         228.000000  
1         228.000000  
2         192.000000  
3         192.000000  
4         192.000000  
...              ...  
1149      177.188997  
1150      197.976865  
1151      186.408429  
1152      174.288210  
1153      185.725828  

[1154 rows x 7 columns]

In [14]:
dfs

Cement (component 1)(kg in a m^3 mixture)  \
0                                   309.934283   
1                                   297.234714   
2                                   312.953771   
3                                   330.460597   
4                                   295.316933   
..                                         ...   
495                                 310.778201   
496                                 279.255077   
497                                 296.193226   
498                                 282.487635   
499                                 272.344005   

     Water (component 4)(kg in a m^3 mixture)  \
0                                  189.261775   
1                                  199.094166   
2                                  166.014324   
3                                  185.629692   
4                                  173.493574   
..                                        ...   
495                                177.188997   
496                                197.976865   
497                                186.408429   
498                                174.288210   
499                                185.725828   

     Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                             7.798711     
1                                             6.849267     
2                                             5.119261     
3                                             3.706126     
4                                             6.396447     
..                                                 ...     
495                                           9.012186     
496                                           9.123007     
497                                           7.416732     
498                                           7.048125     
499                                           6.185054     

     Coarse Aggregate (component 6)(kg in a m^3 mixture)  \
0                                           988.918054     
1                                           922.440714     
2                                           909.090056     
3                                           949.831277     
4                                           941.490769     
..                                                 ...     
495                                        1003.507512     
496                                         948.673937     
497                                         905.906267     
498                                         941.846652     
499                                         912.754868     

     Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day) Grade  
0                                           722.992869         56   C20  
1                                           744.219253         28   C20  
2                                           718.303203         14   C20  
3                                           737.681539         14   C20  
4                                           674.255413         28   C20  
..                                                 ...        ...   ...  
495                                         782.528208         14   C20  
496                                         738.841483         28   C20  
497                                         738.809593         56   C20  
498                                         781.614876         14   C20  
499                                         763.602052         28   C20  

[500 rows x 7 columns]

In [19]:
import pandas as pd

# Assuming your DataFrame is named 'df'
print(combined_df.isna().sum())


Cement (component 1)(kg in a m^3 mixture)                 0
Water  (component 4)(kg in a m^3 mixture)               500
Superplasticizer (component 5)(kg in a m^3 mixture)       0
Coarse Aggregate  (component 6)(kg in a m^3 mixture)    500
Fine Aggregate (component 7)(kg in a m^3 mixture)         0
Age (day)                                                 0
Concrete strength                                       500
Grade                                                     0
Water (component 4)(kg in a m^3 mixture)                654
Coarse Aggregate (component 6)(kg in a m^3 mixture)     654
dtype: int64


In [20]:
combined_df

Cement (component 1)(kg in a m^3 mixture)  \
0                                    380.000000   
1                                    475.000000   
2                                    198.600000   
3                                    198.600000   
4                                    139.600000   
...                                         ...   
1149                                 310.778201   
1150                                 279.255077   
1151                                 296.193226   
1152                                 282.487635   
1153                                 272.344005   

      Water  (component 4)(kg in a m^3 mixture)  \
0                                         228.0   
1                                         228.0   
2                                         192.0   
3                                         192.0   
4                                         192.0   
...                                         ...   
1149                                        NaN   
1150                                        NaN   
1151                                        NaN   
1152                                        NaN   
1153                                        NaN   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                              0.000000     
1                                              0.000000     
2                                              0.000000     
3                                              0.000000     
4                                              0.000000     
...                                                 ...     
1149                                           9.012186     
1150                                           9.123007     
1151                                           7.416732     
1152                                           7.048125     
1153                                           6.185054     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                                 932.0      
1                                                 932.0      
2                                                 978.4      
3                                                 978.4      
4                                                1047.0      
...                                                 ...      
1149                                                NaN      
1150                                                NaN      
1151                                                NaN      
1152                                                NaN      
1153                                                NaN      

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                            594.000000         28   
1                                            594.000000         28   
2                                            825.500000         90   
3                                            825.500000         28   
4                                            806.900000         90   
...                                                 ...        ...   
1149                                         782.528208         14   
1150                                         738.841483         28   
1151                                         738.809593         56   
1152                                         781.614876         14   
1153                                         763.602052         28   

      Concrete strength  Grade  Water (component 4)(kg in a m^3 mixture)  \
0                  36.45   C25                                       NaN   
1                  39.29   C25                                       NaN   
2                  38.07   C25                                       NaN   
3                  28.02   C20                                       NaN   
4                  39.36   C25                                       NaN   
...  

In [18]:
print(dfs.dtypes)


Cement (component 1)(kg in a m^3 mixture)              float64
Water (component 4)(kg in a m^3 mixture)               float64
Superplasticizer (component 5)(kg in a m^3 mixture)    float64
Coarse Aggregate (component 6)(kg in a m^3 mixture)    float64
Fine Aggregate (component 7)(kg in a m^3 mixture)      float64
Age (day)                                                int64
Grade                                                   object
dtype: object


In [25]:
print(combined_df.columns.tolist())


['Cement (component 1)(kg in a m^3 mixture)', 'Water  (component 4)(kg in a m^3 mixture)', 'Superplasticizer (component 5)(kg in a m^3 mixture)', 'Coarse Aggregate  (component 6)(kg in a m^3 mixture)', 'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'Age (day)', 'Concrete strength ', 'Grade', 'Water (component 4)(kg in a m^3 mixture)', 'Coarse Aggregate (component 6)(kg in a m^3 mixture)']


In [26]:
combined_df = combined_df.rename(columns={
    'Water (component 4)(kg in a m^3 mixture)': 'Water Duplicate'
})


In [46]:
combined_df

Cement (component 1)(kg in a m^3 mixture)  \
0                                    380.000000   
1                                    475.000000   
2                                    198.600000   
3                                    198.600000   
4                                    139.600000   
...                                         ...   
1149                                 310.778201   
1150                                 279.255077   
1151                                 296.193226   
1152                                 282.487635   
1153                                 272.344005   

      Water  (component 4)(kg in a m^3 mixture)  \
0                                    228.000000   
1                                    228.000000   
2                                    192.000000   
3                                    192.000000   
4                                    192.000000   
...                                         ...   
1149                                 177.188997   
1150                                 197.976865   
1151                                 186.408429   
1152                                 174.288210   
1153                                 185.725828   

      Superplasticizer (component 5)(kg in a m^3 mixture)  Coarse Aggregate  \
0                                              0.000000          932.000000   
1                                              0.000000          932.000000   
2                                              0.000000          978.400000   
3                                              0.000000          978.400000   
4                                              0.000000         1047.000000   
...                                                 ...                 ...   
1149                                           9.012186         1003.507512   
1150                                           9.123007          948.673937   
1151                                           7.416732          905.906267   
1152                                           7.048125          941.846652   
1153                                           6.185054          912.754868   

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                            594.000000         28   
1                                            594.000000         28   
2                                            825.500000         90   
3                                            825.500000         28   
4                                            806.900000         90   
...                                                 ...        ...   
1149                                         782.528208         14   
1150                                         738.841483         28   
1151                                         738.809593         56   
1152                                         781.614876         14   
1153                                         763.602052         28   

      Concrete strength  Grade  Water Duplicte  
0                  36.45   C25      228.000000  
1                  39.29   C25      228.000000  
2                  38.07   C25      192.000000  
3                  28.02   C20      192.000000  
4                  39.36   C25      192.000000  
...                  ...   ...             ...  
1149                 NaN   C20      177.188997  
1150                 NaN   C20      197.976865  
1151                 NaN   C20      186.408429  
1152                 NaN   C20      174.288210  
1153                 NaN   C20      185.725828  

[1154 rows x 9 columns]

In [33]:
combined_df['Coarse Aggregate'] = combined_df['Coarse Aggregate'].fillna(
    combined_df['Coarse Aggregate (component 6)(kg in a m^3 mixture)']
)


In [39]:
combined_df['Water  (component 4)(kg in a m^3 mixture)'] = combined_df['Water  (component 4)(kg in a m^3 mixture)'].fillna(
    combined_df['Water Duplicate']
)


In [58]:
combined_df.drop(columns=['Concrete strength '], inplace=True)


In [49]:
combined_df.drop('Water  (component 4)(kg in a m^3 mixture)', axis=1, inplace=True)


In [59]:
combined_df

Cement (component 1)(kg in a m^3 mixture)  \
0                                    380.000000   
1                                    475.000000   
2                                    198.600000   
3                                    198.600000   
4                                    139.600000   
...                                         ...   
1149                                 310.778201   
1150                                 279.255077   
1151                                 296.193226   
1152                                 282.487635   
1153                                 272.344005   

      Superplasticizer (component 5)(kg in a m^3 mixture)  Coarse Aggregate  \
0                                              0.000000          932.000000   
1                                              0.000000          932.000000   
2                                              0.000000          978.400000   
3                                              0.000000          978.400000   
4                                              0.000000         1047.000000   
...                                                 ...                 ...   
1149                                           9.012186         1003.507512   
1150                                           9.123007          948.673937   
1151                                           7.416732          905.906267   
1152                                           7.048125          941.846652   
1153                                           6.185054          912.754868   

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day) Grade  \
0                                            594.000000         28   C25   
1                                            594.000000         28   C25   
2                                            825.500000         90   C25   
3                                            825.500000         28   C20   
4                                            806.900000         90   C25   
...                                                 ...        ...   ...   
1149                                         782.528208         14   C20   
1150                                         738.841483         28   C20   
1151                                         738.809593         56   C20   
1152                                         781.614876         14   C20   
1153                                         763.602052         28   C20   

      Water Duplicte  
0         228.000000  
1         228.000000  
2         192.000000  
3         192.000000  
4         192.000000  
...              ...  
1149      177.188997  
1150      197.976865  
1151      186.408429  
1152      174.288210  
1153      185.725828  

[1154 rows x 7 columns]

In [57]:
print(combined_df.columns.tolist())


['Cement (component 1)(kg in a m^3 mixture)', 'Superplasticizer (component 5)(kg in a m^3 mixture)', 'Coarse Aggregate', 'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'Age (day)', 'Concrete strength ', 'Grade', 'Water Duplicte']


In [61]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [62]:
# Feature columns (excluding 'Grade' which is the target)
X = combined_df.drop(columns=['Grade'])

# Target column
y = combined_df['Grade']

# Convert the 'Grade' column to categorical values if necessary
y = y.astype('category')


In [63]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [64]:
# Initialize RandomForestClassifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training data
model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [65]:
# Make predictions on the test set
y_pred = model.predict(X_test)


In [66]:
# Evaluate the model using accuracy, confusion matrix, and classification report
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")


Accuracy: 0.8311688311688312
Confusion Matrix:
[[ 47   3   8]
 [ 10 100  10]
 [  3   5  45]]
Classification Report:
              precision    recall  f1-score   support

         C15       0.78      0.81      0.80        58
         C20       0.93      0.83      0.88       120
         C25       0.71      0.85      0.78        53

    accuracy                           0.83       231
   macro avg       0.81      0.83      0.82       231
weighted avg       0.84      0.83      0.83       231



In [85]:
import numpy as np

# Example input data (replace with your values)
new_data = np.array([[200, 28, 0, 102, 4, 7]])

# Predict the grade using the trained random forest model
predicted_grade = model.predict(new_data)

# Print the predicted grade
print(f"Predicted Grade: {predicted_grade[0]}")


Predicted Grade: C15


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [86]:
from sklearn.model_selection import GridSearchCV

# Define the Random Forest model
rf = RandomForestClassifier(random_state=42)

# Define the parameter grid to tune
param_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
    'bootstrap': [True, False]
}

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')

# Fit GridSearchCV to find the best hyperparameters
grid_search.fit(X_train, y_train)

# Get the best hyperparameters from the grid search
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Train the RandomForest model with the best hyperparameters
best_rf_model = grid_search.best_estimator_

# Evaluate the tuned model on the test set
y_pred_tuned = best_rf_model.predict(X_test)

# Calculate accuracy
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
print(f"Accuracy after Hyperparameter Tuning: {accuracy_tuned * 100:.2f}%")

# Print the classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred_tuned))

# Print the confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_tuned))


Fitting 5 folds for each of 864 candidates, totalling 4320 fits


/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
1440 fits failed out of a total of 4320.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1440 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/u

Best Hyperparameters: {'bootstrap': True, 'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}
Accuracy after Hyperparameter Tuning: 82.68%

Classification Report:
               precision    recall  f1-score   support

         C15       0.79      0.83      0.81        58
         C20       0.93      0.82      0.87       120
         C25       0.69      0.85      0.76        53

    accuracy                           0.83       231
   macro avg       0.80      0.83      0.81       231
weighted avg       0.84      0.83      0.83       231


Confusion Matrix:
 [[48  2  8]
 [10 98 12]
 [ 3  5 45]]


In [87]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [88]:
# Define features (X) and target (y)
X = combined_df.drop('Grade', axis=1)  # Features
y = combined_df['Grade']  # Target variable

In [110]:
# Split the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [114]:
# Initialize the SVM model
svm_model = SVC(kernel='linear')  # Linear kernel

# Train the model
svm_model.fit(X_train, y_train)

SVC(kernel='linear')

In [115]:
y_pred = svm_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)


In [116]:
# Display classification report and confusion matrix
print(f"Accuracy: {accuracy * 100:.2f}%")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 72.29%

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.76      0.73        58
           1       0.72      0.89      0.80       120
           2       0.80      0.30      0.44        53

    accuracy                           0.72       231
   macro avg       0.74      0.65      0.66       231
weighted avg       0.73      0.72      0.70       231


Confusion Matrix:
 [[ 44  12   2]
 [ 11 107   2]
 [  7  30  16]]


In [96]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming your data is in 'combined_df' and that 'Grade' is the target variable

# Split the data into features (X) and target (y)
X = combined_df.drop('Grade', axis=1)
y = combined_df['Grade']

# Convert categorical labels to numeric (if needed)
y = y.map({'C15': 0, 'C20': 1, 'C25': 2})  # Assuming 'Grade' is categorical

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the ExtraTreesClassifier
extra_trees = ExtraTreesClassifier(n_estimators=100, random_state=42)

# Train the model
extra_trees.fit(X_train, y_train)

# Predict on the test set
y_pred = extra_trees.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['C15', 'C20', 'C25']))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 83.00%
Classification Report:
              precision    recall  f1-score   support

         C15       0.73      0.84      0.78        92
         C20       0.90      0.87      0.89       178
         C25       0.80      0.73      0.76        77

    accuracy                           0.83       347
   macro avg       0.81      0.81      0.81       347
weighted avg       0.83      0.83      0.83       347

Confusion Matrix:
[[ 77   8   7]
 [ 16 155   7]
 [ 12   9  56]]


In [100]:
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix

# Prepare the data (assuming you have your train and test data as X_train, y_train, X_test, y_test)
model_xgb = xgb.XGBClassifier(eval_metric='mlogloss')  # Initialize the XGBoost model

# Train the XGBoost model
model_xgb.fit(X_train, y_train)

# Evaluate the model
y_pred_xgb = model_xgb.predict(X_test)
print(f'XGBoost Accuracy: {model_xgb.score(X_test, y_test) * 100:.2f}%')
print(classification_report(y_test, y_pred_xgb))
print(confusion_matrix(y_test, y_pred_xgb))


XGBoost Accuracy: 83.86%
              precision    recall  f1-score   support

           0       0.80      0.83      0.81        92
           1       0.90      0.85      0.88       178
           2       0.76      0.82      0.79        77

    accuracy                           0.84       347
   macro avg       0.82      0.83      0.83       347
weighted avg       0.84      0.84      0.84       347

[[ 76   8   8]
 [ 14 152  12]
 [  5   9  63]]


In [117]:
from sklearn.ensemble import VotingClassifier
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier


# Define the base models
base_models = [
    ('rf', model),  # Pre-trained Random Forest model
    ('et', extra_trees),  # Pre-trained Extra Trees model
    ('svm', svm_model),  # Pre-trained SVM model
    ('xgb', model_xgb)  # Newly trained XGBoost model
]

# Create the hard voting classifier
voting_clf = VotingClassifier(estimators=base_models, voting='hard')

# Train the voting classifier
voting_clf.fit(X_train, y_train)

# Evaluate the ensemble model
voting_accuracy = voting_clf.score(X_test, y_test)
print(f'Voting Classifier Accuracy: {voting_accuracy * 100:.2f}%')

# Get the Classification Report and Confusion Matrix
y_pred = voting_clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Voting Classifier Accuracy: 83.98%
              precision    recall  f1-score   support

           0       0.75      0.86      0.80        58
           1       0.90      0.85      0.88       120
           2       0.82      0.79      0.81        53

    accuracy                           0.84       231
   macro avg       0.82      0.83      0.83       231
weighted avg       0.85      0.84      0.84       231

[[ 50   4   4]
 [ 13 102   5]
 [  4   7  42]]


In [127]:
import pandas as pd
from sklearn.ensemble import VotingClassifier

# Assuming 'voting_clf' is your trained VotingClassifier

# Example of new data (make sure it has the same features as the training data)
new_data = pd.DataFrame({
    'Cement (component 1)(kg in a m^3 mixture)': [200],
    'Superplasticizer (component 5)(kg in a m^3 mixture)': [0],
    'Coarse Aggregate': [0],
    'Fine Aggregate (component 7)(kg in a m^3 mixture)': [102],
    'Age (day)': [28],
    'Water Duplicte': [200]
})

# Predict the grade using the trained voting classifier
predicted_grade = voting_clf.predict(new_data)

# Output the result
print(f"The predicted grade is: {predicted_grade[0]}")


The predicted grade is: 2


Each of the Grade has a number attached to it.
0 is C15,
1 is C20,
2 is C25